version: "3.2"
services:
  app:
    build:
      context: '.'
      dockerfile: Dockerfile-app
    image: colisee/wsaero-app:6.1
    container_name: wsaero-app
    volumes:
      - type: volume
        source: wsaero-vol
        target: /wsaero

  httpd:
    build:
      context: '.'
      dockerfile: Dockerfile-httpd
    image: colisee/wsaero-httpd:6.1
    container_name: wsaero-httpd
    depends_on:
      - app
    ports:
      - "80:80"
    volumes:
      - type: volume
        source: wsaero-vol
        target: /var/www/html/

volumes:
  wsaero-vol:
